name: Lint-phpcs

on:
  workflow_dispatch:
  push:
    branches: [main, 'stable*']
  pull_request:
    branches: [main, 'stable*']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: php-cs
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup PHP
        uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: '8.0'
          coverage: none
          tools: composer, cs2pr, phpcs
      - name: Run phpcs
        run: |
          phpcs --standard=./ruleset.xml --extensions=php,module,inc,install --ignore=node_modules,bower_components,vendor,3rdparty,Migration --warning-severity=0 ./
